# Generated by Django 5.0.14 on 2026-04-11 08:30

import apps.agrupaciones.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bot', models.CharField(default='Asistente', max_length=100)),
                ('tono', models.CharField(choices=[('amigable', 'Amigable'), ('formal', 'Formal'), ('tecnico', 'Técnico')], default='amigable', max_length=20)),
                ('documento_conocimiento', models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[apps.agrupaciones.models.validate_file_size])),
                ('texto_extraido', models.TextField(blank=True)),
                ('agrupacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agrupaciones.agrupacion')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrupaciones.agrupacion')),
            ],
        ),
    ]
