# Generated by Django 5.0.14 on 2026-04-13 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrupacion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracionbot',
            name='nombre_bot',
            field=models.CharField(default='Asistente UNIBot', max_length=100),
        ),
    ]
