# Generated by Django 5.0.14 on 2026-04-20 04:12

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0002_agrupacion_uuid_alter_configuracionbot_nombre_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentoConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='agrupaciones.agrupacion')),
            ],
        ),
    ]
