# Generated by Django 5.0.14 on 2026-04-20 04:37

import apps.agrupaciones.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0003_fragmentoconocimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionbot',
            name='documento_conocimiento',
        ),
        migrations.CreateModel(
            name='DocumentoConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='pdfs/', validators=[apps.agrupaciones.models.validate_file_size])),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='agrupaciones.agrupacion')),
            ],
        ),
        migrations.AddField(
            model_name='fragmentoconocimiento',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='agrupaciones.documentoconocimiento'),
        ),
    ]
