# Generated by Django 5.0.14 on 2026-05-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0009_configuracionbot_clipup_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionbot',
            name='documento_conocimiento',
        ),
        migrations.RemoveField(
            model_name='configuracionbot',
            name='texto_extraido',
        ),
    ]
