# Generated by Django 5.0.14 on 2026-05-10 05:59

import apps.agrupaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0010_remove_configuracionbot_documento_conocimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionbot',
            name='documento_conocimiento',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[apps.agrupaciones.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='configuracionbot',
            name='texto_extraido',
            field=models.TextField(blank=True),
        ),
    ]
