# Generated by Django 5.0.14 on 2026-05-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0011_configuracionbot_documento_conocimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionbot',
            name='documento_conocimiento',
        ),
    ]
