# Generated by Django 5.0.14 on 2026-05-10 06:02

import apps.agrupaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0012_remove_configuracionbot_documento_conocimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionbot',
            name='documento_conocimiento',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[apps.agrupaciones.models.validate_file_size]),
        ),
    ]
