# Generated by Django 5.0.14 on 2026-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_inscripcion_confirmacion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='acta_notion_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evento',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='certificado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='certificado_enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='recordatorio_24h_enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='recordatorio_2h_enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
