# Generated by Django 5.0.14 on 2026-04-13 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0002_agrupacion_uuid_alter_configuracionbot_nombre_bot'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_chats', to='agrupaciones.agrupacion')),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
